"""Add submission date

Revision ID: 13d7c885ef1c
Revises: 825b3f84b58c
Create Date: 2025-08-27 18:07:32.197045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '13d7c885ef1c'
down_revision: Union[str, None] = '825b3f84b58c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answersession', sa.Column('submitted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answersession', 'submitted_at')
    # ### end Alembic commands ###
