"""Link user to forms

Revision ID: 61304c08351e
Revises: 1fe090bc7a21
Create Date: 2025-06-30 16:35:40.118982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '61304c08351e'
down_revision: Union[str, None] = '1fe090bc7a21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form', sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_foreign_key(None, 'form', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'form', type_='foreignkey')
    op.drop_column('form', 'user_id')
    # ### end Alembic commands ###
