"""Feat/deadlines: Add deadline and submission limit fields

Revision ID: 825b3f84b58c
Revises: e1b5052f4803
Create Date: 2025-07-09 09:35:15.687241

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "825b3f84b58c"
down_revision: Union[str, None] = "e1b5052f4803"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "form", sa.Column("submissions_limit", sa.Integer(), nullable=True)
    )
    op.add_column(
        "form",
        sa.Column(
            "submissions", sa.Integer(), server_default="0", nullable=False
        ),
    )
    op.add_column("form", sa.Column("deadline", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("form", "deadline")
    op.drop_column("form", "submissions")
    op.drop_column("form", "submissions_limit")
    # ### end Alembic commands ###
